amanco/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from .import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.home, name="home"),
    url(r'^search/$', views.search, name="search"),
    url(r'^products/', include('products.urls')),
    url(r'^carts/', include('carts.urls')),
    url(r'^accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/urls.py
from django.conf.urls import url
from . import views

app_name = "carts"

urlpatterns = [
    # url(r'^$', views.carts, name = "carts"),
    url(r'^$', views.carts_views, name="carts"),
    url(r'^(?P<id>[\d]+)/$', views.remove_from_cart, name="remove_from_cart"),
    url(r'^(?P<slug>[\w-]+)/$', views.add_to_cart, name="add_to_cart"),
]

products/urls.py
from django.conf.urls import url
from . import views

app_name = "products"

urlpatterns = [
    url(r'^$', views.products_list, name = "products_list"),
    url(r'^(?P<slug>[\w-]+)/$', views.product_detail, name="product_detail"),
]

carts/models.py
from django.db import models
from products.models import Product, ProductVariation
# Create your models here.

class CartItem(models.Model):
    cart = models.ForeignKey("Cart", on_delete=models.CASCADE, blank=True, null=True)
    product = models.ForeignKey(Product, null=True, blank=True, on_delete=models.CASCADE)
    variation = models.ManyToManyField(ProductVariation)
    notes = models.TextField(null=True, blank=True)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return self.product.title

class Cart(models.Model):
    # items = models.ManyToManyField(CartItem)
    # products = models.ManyToManyField(Product)
    total = models.DecimalField(decimal_places=2, max_digits=100, default=0.0)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    update = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        # return "%s" %(self.id)
        return "Cart id: %s" %(self.id)

carts/views.py
from django.shortcuts import render, redirect
from .models import Cart, CartItem
from products.models import Product, ProductVariation
# Create your views here.

def carts_views(request):
    try:
        the_id = request.session['cart_id']
    except:
        the_id = None
    if the_id:
        cart = Cart.objects.get(id=the_id)
        context = {'cart': cart}
    else:
        context = {'empty': True}
    templates = "carts/carts_view.html"
    return render(request, templates, context)

def remove_from_cart(request, id):
    try:
        the_id = request.session['cart_id']
    except:
        the_id = None
    if the_id:
        cart = Cart.objects.get(id=the_id)
        cart_item = CartItem.objects.get(id=id)
        cart_item.delete()
        cart.total = 0
        for item in cart.cartitem_set.all():
            cart.total += item.product.price*item.quantity
        request.session['items_count'] = cart.cartitem_set.count()
        cart.save()
    return redirect("carts:carts")

def add_to_cart(request, slug):
    request.session.set_expiry(300)
    if request.method == "POST":
        qty = int(request.POST['qty'])
        if qty > 0:
            try:
                product = Product.objects.get(slug=slug)
            except Product.DoesNotExist:
                pass
            except:
                pass
            product_var = []
            for item in request.POST:
                val = request.POST[item]
                try:
                    variation = ProductVariation.objects.get(products=product, category__iexact=item, title__iexact=val)
                    product_var.append(variation)
                except:
                    pass
            try:
                the_id = request.session['cart_id']
            except:
                new_cart = Cart()
                new_cart.save()
                request.session['cart_id'] = new_cart.id
                the_id = new_cart.id
            cart = Cart.objects.get(id=the_id)

            cart_item = CartItem.objects.create(cart=cart, product=product)
            print(product_var)
            if len(product_var) > 0:
                for vars in product_var:
                    cart_item.variation.add(vars)
            cart_item.quantity = qty
            cart_item.save()
            cart.total = 0
            for item in cart.cartitem_set.all():
                cart.total += item.product.price*item.quantity

            cart.save()
            request.session['items_count'] = cart.cartitem_set.count()
        return redirect("carts:carts")
    else:
        return redirect("carts:carts")

carts/templates/carts/carts_view.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block head_title %}
Welcome to Products
{% endblock %}

{% block content %}
{% if empty %}
<h1 class="text-center">Your Cart is Empty, please keep shopping</h1>
{% else %}
<div class="container">
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Count</th>
        <th scope="col">Item</th>
        <th scope="col">Qty</th>
        <th scope="col">Price</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart.cartitem_set.all %}
      <tr>
        <td>1</td>
        <td><a href="{% url 'products:product_detail' slug=item.product.slug%}">{{item.product.title}}</a>
          <ul>
            {% for variation in item.variation.all %}
            <li>{{variation}}</li>
            {% endfor %}
          </ul>
        </td>
        <td>{{item.quantity}}</td>
        <td>{{item.product.price}}</td>
        <td><a href="{% url 'carts:remove_from_cart' id=item.id %}">Remove</a></td>
      </tr>
      {% endfor %}
      <tr>
        <td></td>
        <td></td>
        <td></td>
        <td><p>Total: {{cart.total}}</p></td>
        <td></td>
      </tr>
    </tbody>

  </table>
</div>
{% endif %}
<!-- <h1>{{slug}}</h1>
<p>Hello! Aman it is correct</p> -->
{% endblock %}