amanco/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from .import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.home, name="home"),
    url(r'^search/$', views.search, name="search"),
    url(r'^products/', include('products.urls')),
    url(r'^carts/', include('carts.urls')),
    url(r'^accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/urls.py
from django.conf.urls import url
from . import views

app_name = "carts"

urlpatterns = [
    # url(r'^$', views.carts, name = "carts"),
    url(r'^$', views.carts_views, name="carts"),
    url(r'^(?P<id>[\d]+)/$', views.remove_from_cart, name="remove_from_cart"),
    url(r'^(?P<slug>[\w-]+)/$', views.add_to_cart, name="add_to_cart"),
]

products/urls.py
from django.conf.urls import url
from . import views

app_name = "products"

urlpatterns = [
    url(r'^$', views.products_list, name = "products_list"),
    url(r'^(?P<slug>[\w-]+)/$', views.product_detail, name="product_detail"),
]

products/models.py
from django.urls import reverse
from django.db import models

# Create your models here.

class Product(models.Model):
    title = models.CharField(max_length=255, blank=False)
    description = models.TextField(null=True, blank=True)
    price = models.DecimalField(decimal_places=2, max_digits=100, default=True)
    slug = models.SlugField(unique=True)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    update = models.DateTimeField(auto_now_add=False, auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        unique_together = ('title', 'slug')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("products:product_detail", kwargs={"slug":  self.slug})

class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete='CASCADE')
    image = models.ImageField(upload_to='products/images', default="products/images/default.png")
    featured = models.BooleanField(default=False)
    thumbnail = models.BooleanField(default=False)
    active = models.BooleanField(default=True)
    update = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return self.product.title

class ProductVariationManager(models.Manager):
    def all(self):
        return super(ProductVariationManager, self).filter(active=True)
    def sizes(self):
        return self.all().filter(category='size')
    def colors(self):
        return self.all().filter(category='color')


VAR_CATEGORIES = (
    ('size', 'size'),
    ('color', 'color'),
)

class ProductVariation(models.Model):
    products = models.ForeignKey(Product, on_delete=models.CASCADE)
    active = models.BooleanField(default=True)
    title = models.CharField(max_length=100)
    category = models.CharField(max_length=100, choices=VAR_CATEGORIES)
    objects = ProductVariationManager()

    def __str__(self):
        return self.title

templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
  <head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
  <meta name="generator" content="Jekyll v3.8.6">
  <title>{% block head_title %}{% endblock %} Ecommerce</title>
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" crossorigin="anonymous">

  <style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      -ms-user-select: none;
      user-select: none;
    }

    .background-img-thumb{
      width:100px;
      height:100px;
      margin-left: auto;
      margin-right: auto;
      background-image: url({% static 'img/default.png'%});
      background-size:cover;
      background-position:center;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }
    .pull-right{
      right:0;
      position: absolute;
    }
  </style>
</head>

<body>
  <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
    <a class="navbar-brand" href="{%url 'home'%}">Ecommerce</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <!-- <li class="nav-item active">
          <a class="nav-link" href="{%url 'home'%}">Home <span class="sr-only">(current)</span></a>
        </li> -->
      </ul>
      <form class="form-inline mt-2 mt-md-0" action="/search/">
        <input class="form-control mr-sm-2" type="text" placeholder="Search" name="q" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
      <ul class="navbar-nav mt-2 mt-md-0">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'carts:carts' %}">Cart
            <span class="badge badge-light">
              {% if request.session.items_count %}
              {{request.session.items_count}}
              {% else %}
              0
              {% endif %}
            </span>
          </a>
        </li>
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="#">Account</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>
  {% block content %}
  {% endblock %}
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  <script>window.jQuery || document.write('<script src="/docs/4.4/assets/js/vendor/jquery.slim.min.js"><\/script>')</script><script src="https://getbootstrap.com/docs/4.4/dist/js/bootstrap.bundle.min.js" integrity="sha384-6khuMg9gaYr5AxOqhkVIODVIvm9ynTT5J4V1cfthmT+emCG6yVmEZsRHdxlotUnm" crossorigin="anonymous"></script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block head_title %}
Welcome to
{% endblock %}
{% block content%}
<!-- <main role="main" class="container">
  <div class="jumbotron">
    <h1>{{username}}</h1>
    <p class="lead">This example is a quick exercise to illustrate how the top-aligned navbar works. As you scroll, this navbar remains in its original position and moves with the rest of the page.</p>
    <a class="btn btn-lg btn-primary" href="/docs/4.4/components/navbar/" role="button">View navbar docs &raquo;</a>
  </div>
</main> -->

<div class="container">
  <div class="row">
    {% for product in products %}
    <div class="col-lg-4 col-md-6 col-sm-12">
      <div class="thumbnail">
        {% if product.productimage_set.all %}
        {% for pimage in product.productimage_set.all %}
        <div class="background-img-thumb" style="
          background-image: url('{{pimage.image.url}}');">
        </div>
        {% endfor %}
        {% else %}
        <div class="background-img-thumb">
        </div>
        {% endif %}
        <div class="caption">
          <h3>{{product.title}}</h3>
          <p>{{product.description|truncatechars:15}}</p>
          <p align="center"><a href="{{product.get_absolute_url}}" class="btn btn-primary btn-block">Product Detail</a></p>
        </div>
      </div>
      <br/>
    </div>
    {% cycle "" "" "</div><br/><hr><div class='row'>" %}
    {% endfor %}
  </div>
</div>
{% endblock%}

templates/search.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
<div class="container">
  <table class="table">
    <thead>
      <th scope="col">Images</th>
      <th scope="col">Products</th>
      <th scope="col">Description</th>
    </thead>
    <tbody>
    {% for product in products %}
    <tr>
      <td >
        <div class="thumbnail">
          {% if product.productimage_set.all %}
          {% for pimage in product.productimage_set.all %}
          <div class="background-img-thumb" style="
            background-image: url('{{pimage.image.url}}')">
          </div>
          {% endfor %}

          {% else %}
          <div class="background-img-thumb">
          </div>
          {% endif %}
        </div>
      </td>
      <td>
        <a href="{% url 'products:product_detail' slug=product.slug%}">
          {{product.title}}
        </a>
      </td>
      <td><p>{{product.description|truncatechars:15}}</p></td>
    </tr>
    {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}