amanco/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from .import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.home, name="home"),
    url(r'^search/$', views.search, name="search"),
    url(r'^products/', include('products.urls')),
    url(r'^carts/', include('carts.urls')),
    url(r'^accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/urls.py
from django.conf.urls import url
from . import views

app_name = "carts"

urlpatterns = [
    # url(r'^$', views.carts, name = "carts"),
    url(r'^$', views.carts_views, name="carts"),
    url(r'^(?P<id>[\d]+)/$', views.remove_from_cart, name="remove_from_cart"),
    url(r'^(?P<slug>[\w-]+)/$', views.add_to_cart, name="add_to_cart"),
]

products/urls.py
from django.conf.urls import url
from . import views

app_name = "products"

urlpatterns = [
    url(r'^$', views.products_list, name = "products_list"),
    url(r'^(?P<slug>[\w-]+)/$', views.product_detail, name="product_detail"),
]

products/models.py
from django.urls import reverse
from django.db import models

# Create your models here.

class Product(models.Model):
    title = models.CharField(max_length=255, blank=False)
    description = models.TextField(null=True, blank=True)
    price = models.DecimalField(decimal_places=2, max_digits=100, default=True)
    slug = models.SlugField(unique=True)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    update = models.DateTimeField(auto_now_add=False, auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        unique_together = ('title', 'slug')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("products:product_detail", kwargs={"slug":  self.slug})

class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete='CASCADE')
    image = models.ImageField(upload_to='products/images', default="products/images/default.png")
    featured = models.BooleanField(default=False)
    thumbnail = models.BooleanField(default=False)
    active = models.BooleanField(default=True)
    update = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return self.product.title

class ProductVariationManager(models.Manager):
    def all(self):
        return super(ProductVariationManager, self).filter(active=True)
    def sizes(self):
        return self.all().filter(category='size')
    def colors(self):
        return self.all().filter(category='color')


VAR_CATEGORIES = (
    ('size', 'size'),
    ('color', 'color'),
)

class ProductVariation(models.Model):
    products = models.ForeignKey(Product, on_delete=models.CASCADE)
    active = models.BooleanField(default=True)
    title = models.CharField(max_length=100)
    category = models.CharField(max_length=100, choices=VAR_CATEGORIES)
    objects = ProductVariationManager()

    def __str__(self):
        return self.title

products/views.py
from django.shortcuts import render
from .models import Product

# Create your views here.

def products_list(request):
    products = Product.objects.all().order_by('update')
    context = {'products': products}
    template = 'products/products.html'
    return render(request, template, context)

def product_detail(request, slug):
    product = Product.objects.get(slug=slug)
    context = {'product': product}
    template = "products/product_detail.html"
    return render(request, template, context)

products/templates/products/product_detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block head_title %}
Welcome to Products {{product.title}}
{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-6 col-lg-4">
      {% if product.productimage_set.all %}
      {% for pimage in product.productimage_set.all %}
      {% if pimage.featured %}
      <img class="img-thumbnail" src="{{pimage.image.url}}" alt="item-image">
      {% else %}
      <img class="img-thumbnail" src={% static 'img/default.png'%} alt="item-image">
      {% endif %}
      {% endfor %}
      {% else %}
      <img class="img-thumbnail" src={% static 'img/default.png'%} alt="item-image">
      {% endif %}
      <hr/>
    </div>
    <div class="col-sm-12 col-md-8 col-lg-8">
      <!-- <p class="text-right">Right aligned text on all viewport sizes.</p> -->
      <div class="row">
        <div class="col-sm-12 col-md-4">
          <h3>{{product.title}}</h3>
        </div>
        <div class="col-sm-12 col-md-4">
          <form method="post" action="{% url 'carts:add_to_cart' slug=product.slug  %}">
            {% csrf_token %}
            <div class="form-group row">
              <div class="col">
                <label for="qty"> Product:</label>
                <input type="number" class="form-control" name="qty" value="1" id="qty">
              </div>
            </div>
            <input class="btn btn-secondary btn-lg btn-block" type="submit" value="Add to Cart">
            {% if product.productvariation_set.all %}
            <!-- <h1>Hello</h1> -->
            {% if product.productvariation_set.sizes %}
            <!-- <h1>Size</h1> -->
            <label for="size">Size:</label>
            <select name="size" id="size" class="btn-lg btn-block">
              {% for productvariation in product.productvariation_set.sizes %}
              <option value="{{productvariation.title}}">{{productvariation.title}}</option>
              {% endfor %}
            </select>
            {% endif %}
            {% if product.productvariation_set.colors %}
            <label for="color">Color:</label>
            <select name="color" id="color" class="btn-lg btn-block form-control">
              {% for productvariation in product.productvariation_set.colors %}
              <option value="{{productvariation.title}}">{{productvariation.title}}</option>
              {% endfor %}
            </select>
            {% endif %}
            {% endif %}
          </form>
        </div>
      </div>
      <br><br>
      <hr>
      <h5>Price: {{product.price}}</h5>
      <hr>
      <p class="text-justify">{{ product.description|linebreaks }}</p>
    </div>
  </div>
</div>
{% endblock %}

products/templates/products/products.html
{% extends 'base.html' %}

{% block head_title %}
Welcome to Products
{% endblock %}

{% block content %}
<ul>
  {% for Product in products %}
  <li>{{Product}}{{Product.price}}</li>
  {% endfor %}
</ul>
{% endblock %}